# frozen_string_literal: true

module CleaningVerification
  # TASK 3b. Generated by an AI and merged without review. Read it like a
  # colleague's PR and fix what's wrong. Builds an operator's weekly digest.
  class AvailabilitySummary
    def initialize(operator, from: Time.current, days: 7)
      @operator = operator
      @from = from
      @days = days
    end

    def call
      instances = BookingInstance
                    .joins(facility: :venue)
                    .where(facilities: { venues: { operator_id: @operator.id } })
                    .where(starts_at: @from..(@from + @days.days))
                    .includes(facility: :venue)
                    .order("starts_at ASC")

      rows = instances.map do |booking_instance|
        {
          venue: booking_instance.facility.venue.name,
          operator: booking_instance.facility.venue.operator.name,
          facility: booking_instance.facility.name,
          starts_at: booking_instance.starts_at,
          verification: booking_instance.verification_status
        }
      end

      # TBD: Move auto_flag_stale method to rake job and trigger it one time per hour by cron
      # Moved and optimized the code to FlagStaleBookingsJob.perform
      #auto_flag_stale!(instances)

      { generated_at: Time.current, rows: rows }
    end
  end
end
