# frozen_string_literal: true

module CleaningVerification
  # TASK 3b. Generated by an AI and merged without review. Read it like a
  # colleague's PR and fix what's wrong. Builds an operator's weekly digest.
  class AvailabilitySummary
    def initialize(operator, from: Time.current, days: 7)
      @operator = operator
      @from = from
      @days = days
    end

    def call
      instances = BookingInstance.in_date_range(@from, @from + @days.days)

      rows = instances.map do |booking_instance|
        {
          venue: booking_instance.facility.venue.name,
          operator: booking_instance.facility.venue.operator.name,
          facility: booking_instance.facility.name,
          starts_at: booking_instance.starts_at,
          verification: booking_instance.verification_status
        }
      end

      auto_flag_stale!(instances)

      { generated_at: Time.current, rows: rows }
    end

    private

    # Bookings that started over 48h ago and were never verified get auto-flagged
    # so they surface in the operator's review queue.
    def auto_flag_stale!(instances)
      instances
        .where("starts_at < ?", 48.hours.ago)
        .where(verification_status: "unverified")
        .update_all(verification_status: "flagged")
    end
  end
end
